# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0002_IMPORT_DATA'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransformationProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTransformationProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('uri', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=30)),
                ('code_field', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaboliteIdentificationProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaboliteIdentificationProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('uri', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=30)),
                ('code_field', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleCollectionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCollectionProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('uri', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=30)),
                ('code_field', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='investigation',
            name='description',
            field=models.TextField(help_text='Investigation description'),
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(help_text='Study description'),
        ),
        migrations.AddField(
            model_name='samplecollectionprocess',
            name='samplecollectionprocess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misa.SampleCollectionProtocol'),
        ),
        migrations.AddField(
            model_name='metaboliteidentificationprocess',
            name='metaboliteidentificationprotocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misa.MetaboliteIdentificationProtocol'),
        ),
        migrations.AddField(
            model_name='datatransformationprocess',
            name='datatransformationprotocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misa.DataTransformationProtocol'),
        ),
        migrations.AddField(
            model_name='studysample',
            name='samplecollectionprocess',
            field=models.ForeignKey(blank=True, help_text='The sample collection process used (will be added automatically)', null=True, on_delete=django.db.models.deletion.CASCADE, to='misa.SampleCollectionProcess'),
        ),
    ]
