# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0002_CUSTOM_IMPORT_DATA'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontologyterm',
            old_name='label',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ontologyterm',
            name='link',
        ),
    ]
