# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0003_auto_20180522_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontologyterm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misa.OntologyTerm')),
            ],
        ),
        migrations.RemoveField(
            model_name='organism',
            name='name',
        ),
        migrations.AlterField(
            model_name='studyfactor',
            name='ontologyterm_type',
            field=models.ForeignKey(blank=True, help_text='The type for the value e.g. if a concentration what unit. If the ontology term is not available please add here ()', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ontologyterm_type', to='misa.OntologyTerm', verbose_name='Ontology Term (type)'),
        ),
        migrations.AlterField(
            model_name='studyfactor',
            name='ontologyterm_value',
            field=models.ForeignKey(blank=True, help_text='The value, e.g. if  concentration what unit. If the ontology term is not available please add here ()', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ontologyterm_value', to='misa.OntologyTerm', verbose_name='Ontology Term (type)'),
        ),
    ]
