# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0003_auto_20180727_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polaritytype',
            name='ontologyterm',
        ),
        migrations.AddField(
            model_name='polaritytype',
            name='ontologyterm',
            field=models.ManyToManyField(to='misa.OntologyTerm'),
        ),
    ]
