# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0003_auto_20180629_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='assaydetail',
            name='datatransformationprocess',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='misa.DataTransformationProcess'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assaydetail',
            name='metaboliteidentifcationprocess',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='misa.MetaboliteIdentificationProcess'),
            preserve_default=False,
        ),
    ]
