# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0004_auto_20180727_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polaritytype',
            options={},
        ),
    ]
