# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0004_auto_20180704_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assaydetail',
            name='datatransformationprocess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misa.DataTransformationProcess'),
        ),
        migrations.AlterField(
            model_name='assaydetail',
            name='metaboliteidentifcationprocess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misa.MetaboliteIdentificationProcess'),
        ),
    ]
