# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0007_auto_20180523_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysample',
            name='organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misa.Organism'),
        ),
        migrations.AddField(
            model_name='studysample',
            name='organism_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misa.OrganismPart'),
        ),
        migrations.AlterField(
            model_name='studysample',
            name='sampletype',
            field=models.ForeignKey(help_text='This is an internal category that helps with some downstream processing essentialy ANIMAL covers all biological samples, COMPOUND is for chemical standards or non biological samples, and BLANK is for any samples that represent the blank (e.g. for  blank subtraction)', on_delete=django.db.models.deletion.CASCADE, to='misa.SampleType'),
        ),
    ]
