# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0008_auto_20180523_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ontologyterm',
            field=models.ForeignKey(help_text="If the ontology term is not available, please  <a target='_blank' href='/misa/search_ontologyterm/'>add</a>.", on_delete=django.db.models.deletion.CASCADE, to='misa.OntologyTerm'),
        ),
        migrations.AlterField(
            model_name='organismpart',
            name='ontologyterm',
            field=models.ForeignKey(help_text="If the ontology term is not available, please  <a target='_blank' href='/misa/search_ontologyterm/'>add</a>.", on_delete=django.db.models.deletion.CASCADE, to='misa.OntologyTerm'),
        ),
        migrations.AlterField(
            model_name='studysample',
            name='organism',
            field=models.ForeignKey(blank=True, help_text="If factor not available then please   <a target='_blank' href='/misa/create_organism/'>add</a>.", null=True, on_delete=django.db.models.deletion.CASCADE, to='misa.Organism'),
        ),
        migrations.AlterField(
            model_name='studysample',
            name='organism_part',
            field=models.ForeignKey(blank=True, help_text="If organism part not available then please   <a target='_blank' href='/misa/create_organismpart/'>add</a>.", null=True, on_delete=django.db.models.deletion.CASCADE, to='misa.OrganismPart'),
        ),
        migrations.AlterField(
            model_name='studysample',
            name='studyfactor',
            field=models.ManyToManyField(blank=True, help_text="If factor not available then please   <a target='_blank' href='/misa/sfcreate/'>add</a>.", to='misa.StudyFactor'),
        ),
    ]
