# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0010_organismpart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfactor',
            name='ontologyterm_value',
            field=models.ForeignKey(blank=True, help_text="The value, e.g. if  wild type, 5 Mol, etc If the ontology term is not available please  <a target='_blank' href='/misa/search_ontologyterm/'>add</a>.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ontologyterm_value', to='misa.OntologyTerm', verbose_name='Ontology Term (value)'),
        ),
    ]
