# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misa', '0012_auto_20180523_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chromatographytype',
            name='ontologyterm',
        ),
        migrations.AddField(
            model_name='chromatographytype',
            name='ontologyterm',
            field=models.ManyToManyField(null=True, to='misa.OntologyTerm'),
        ),
    ]
